name: 'Container Pull request Build & Deploy'

on:
  workflow_run:
    workflows: ["Terraform Pull Request Plan & Apply"]     # must match the name: field in terraform-pr.yaml
    types:
      - completed
    conclusions: 
      - success

permissions:
  id-token: write
  contents: read

env:
  ENVIRONMENT: pr${{ github.event.workflow_run.pull_requests[0].number }} # Get the workflow run(which triggers THIS pipeline) and get the PR ID of that workflow run.
  IMAGE_NAME: ${{ github.repository }}
  ACR_NAME: fozzenrdotnetregpr${{ github.event.workflow_run.pull_requests[0].number }}
  ACR_LOGIN_SERVER: fozzenrdotnetregpr${{ github.event.workflow_run.pull_requests[0].number }}.azurecr.io

jobs:

  build:
    runs-on: ubuntu-latest
    environment: pr
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_sha }}


      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR via OIDC
        run: az acr login --name $ACR_NAME

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}

      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ReactApp1.Server/Dockerfile
          cache-from: type=gha
          tags: ${{ steps.meta.outputs.tags }}


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: pr
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.workflow_run.head_sha }}

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR via OIDC
        run: az acr login --name $ACR_NAME

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: fozzen-reactdotnet-appsvc${{ env.ENVIRONMENT }}
          images: ${{ steps.meta.outputs.tags }}