name: "Container Plan & Apply"

on:
  push:
    branches:
      - dev
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

env:
  ENVIRONMENT: ${{ github.ref_name == 'dev' && 'dev'
                || github.ref_name == 'test' && 'test'
                || github.ref_name == 'main' && 'prod' }}
  IMAGE_NAME: ${{ github.repository }}
  ACR_NAME: fozzenreactdotnetreg${{ github.ref_name == 'main' && 'prod' || github.ref_name }}
  ACR_LOGIN_SERVER: fozzenreactdotnetreg${{ github.ref_name == 'main' && 'prod' || github.ref_name }}.azurecr.io

jobs:

  build:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}

    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR via OIDC
        run: az acr login --name $ACR_NAME

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}

      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          dockerfile: ./ReactApp1.Server/Dockerfile
          cache-from: type=gha
          tags: ${{ steps.meta.outputs.tags }}

  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'prod' || github.ref_name }}
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Login to ACR via OIDC
        run: az acr login --name $ACR_NAME

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: fozzen-reactdotnet-appsvc${ENVIRONMENT}
          images: ${{ steps.meta.outputs.tags }}