name: 'Terraform Pull Request Plan & Apply'

on:
  pull_request:
    branches:
      - dev # Only runs on PRs targeting dev branch
    types: [opened, reopened] # Triggers on when you open or re-open a pull request

permissions:
  id-token: write
  contents: read

env:
    location: westeurope
    ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
    ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
    ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
    environment: pr${{ github.event.pull_request.number }} # Only used for the environment name, not auth
    RESOURCE_GROUP: prenv-management-RG # Must already be created
    STORAGE_ACCOUNT: tfstateprenvfozzen # Created via the bootstrap

jobs:
  setup-pr-backend:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    outputs:
      container_name: ${{ steps.bootstrap.outputs.container_name }} # Outputs from the bootstrap-pr.sh
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Run PR backend bootstrap
        id: bootstrap
        run: bash .github/workflows/bootstrap-pr.sh ${{ github.event.pull_request.number }}

  terraform-pr:
        if: github.event_name == 'pull_request'
        needs: [setup-pr-backend]
        name: Deploy Terraform to PR
        runs-on: ubuntu-latest
        # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
        defaults:
          run:
            working-directory: .github/Terraform/pr
            shell: bash

        steps:
        # Checkout the repository to the GitHub Actions runner
        - name: Checkout
          uses: actions/checkout@v3

        # Install the latest version of Terraform CLI 
        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v1

        # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
        - name: Terraform Init
          run: |
            terraform init \
              -backend-config="resource_group_name=$RESOURCE_GROUP" \
              -backend-config="storage_account_name=$STORAGE_ACCOUNT" \
              -backend-config="container_name=tfstate-$environment" \
              -backend-config="key=terraform.tfstate" \
              -backend-config="use_oidc=true"


        - name: Terraform Format
          run: terraform fmt -recursive

        # Validate before Planning
        - name: Terraform Validate
          run: terraform validate 


        - name: Terraform Plan
          run: terraform plan -input=false -var location=$location -var environment=$environment
          
        - name: Terraform Apply
          run: terraform apply -auto-approve  -input=false -var location=$location -var environment=$environment