
name: Cleanup PR Terraform Backend

on:
  pull_request:
    branches:
      - dev    # only run on PRs targeting main
    types: [closed] # targets both merge and manually close PR

permissions:
  id-token: write
  contents: read

env:
  location: westeurope
  environment: pr${{ github.event.pull_request.number }}
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  BACKEND_CONTAINER: tfstate-pr${{ github.event.pull_request.number }}
  PR_ID: ${{ github.event.pull_request.number }}
  STORAGE_ACCOUNT: tfstateprenvfozzen
  RESOURCE_GROUP: prenv-management-RG

jobs:
  destroy:      
    name: Terraform Destroy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .github/Terraform/pr
        shell: bash

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    - name: Terraform Init
      run: |
        terraform init \
          -backend-config="resource_group_name=$RESOURCE_GROUP" \
          -backend-config="storage_account_name=$STORAGE_ACCOUNT" \
          -backend-config="container_name=tfstate-$environment" \
          -backend-config="key=terraform.tfstate" \
          -backend-config="use_oidc=true"

    - name: Terraform Format
      run: terraform fmt -recursive

    - name: Terraform Validate
      run: terraform validate 

    - name: Terraform Plan (Destroy)
      run: terraform plan -destroy -input=false -var location=$location -var environment=$environment

    - name: Terraform Destroy
      run: terraform destroy -auto-approve -input=false -var location=$location -var environment=$environment
